### PR TITLE
Add Travis & misc build tweaks

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
Btw @non if you enable Travis for this repo, you need to close and open this PR to get it to run.

So we can Travis check the PR that enables Travis.

**Comment by mikejcurry** [comment]
Just as an FYI, based on my assumption that the build for scala 2.10 will happen in a separate build from scala 2.11 (and it is just an assumption because I'm not super familiar with travis config), then I think this will fail on 2.10 until #6 is through, because the scala 2.10 tests won't execute unless 2.11 has been built at the moment. 

Looks good though!

**Comment by dwijnand** [comment]
Looks from your PR that that is very possible. But FWIW it's also workaround-able (while your PR is blocked) by reordering `crossScalaVersions` and changing the Travis script to cross build.

**Comment by mikejcurry** [comment]
Cool, just thinking about this though, might be nice verification if this one is failing without workaround and the other PR resolves it once this is through, rather than trying to do workarounds and then reverse them.

**Pull request closed without merging**
